repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/golangci/golangci-lint'
    rev: v1.45.2
    hooks:
      - id: golangci-lint
  - repo: local
    hooks:
      - id: go-test
        name: go-test
        entry: go test -race ./...
        types: [ go ]
        language: golang
        pass_filenames: false
        always_run: true
        verbose: true
