// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/nksv-tech/gendata-backend/internal/config"
	"github.com/nksv-tech/gendata-backend/internal/server"
	"github.com/nksv-tech/gendata-backend/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(configConfig *config.Config, logger log.Logger) (*kratos.App, func(), error) {
	genDataService := service.NewGenDataService()
	limiter := server.NewRateLimiter(configConfig)
	v := server.NewMiddlewares(configConfig, logger, limiter)
	cMux := server.NewMux(configConfig)
	tlsConfig := server.NewTLS(configConfig)
	grpcServer := server.NewGRPCServer(configConfig, genDataService, v, cMux, logger, tlsConfig)
	httpServer := server.NewHTTPServer(configConfig, genDataService, v, cMux, logger, tlsConfig)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
